# Generated by Django 2.0 on 2018-02-11 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FundamentosPlay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('leader', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='FundamentosPlay.LeaderBoard')),
                ('nombre', models.CharField(default='Nombres y Appelidos', max_length=200)),
                ('duracion', models.IntegerField()),
                ('segundos', models.IntegerField(default=0)),
                ('minutos', models.IntegerField(default=0)),
                ('horas', models.IntegerField(default=0)),
            ],
        ),
    ]
