# Generated by Django 2.0 on 2018-02-11 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FundamentosPlay', '0002_leaderboard_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FundamentosPlay.LeaderBoard'),
        ),
    ]
