# Generated by Django 2.0 on 2018-02-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundamentosPlay', '0004_auto_20180211_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='foto',
            field=models.CharField(default='http://bandera.inquirer.net/files/2016/06/BLIND-ITEM-MALE-0624.jpg', max_length=400),
        ),
    ]
